spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost/v2/oauth2/code/kakao

front-server:
  domain: http://localhost:3000

cookie:
  domain: localhost
