server:
  port: 80

spring:
  jpa:
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  output:
    ansi:
      enabled: always
