spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true

  datasource:
    url: jdbc:mysql://localhost:3306/wcnc
    username: root
    password: 12345678

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost/v2/oauth2/code/kakao
          naver:
            redirect-uri: http://localhost/v2/oauth2/code/naver

front-server:
  domain: http://localhost:3000

cookie:
  domain: localhost
