server:
  port: 80

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  output:
    ansi:
      enabled: always

cookie:
  max-age: 7776000  # 60*60*24*90, 90일

jwt:
  secret: ${JWT_SECRET}