spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        '[format_sql]': false

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://api.washcar.me/v2/oauth2/code/kakao

front-server:
  domain: https://www.washcar.me

cookie:
  domain: washcar.me
