spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        '[format_sql]': false

  datasource:
    # AWS RDS 값 인코딩해서 넣을 것
    url:
    username:
    password: ENC(N0e5gyuFwpblqQOzbJtC+9dA3iQGMoIQ6LG7EntaIkMaDbh9txHuk01CBo+kdednZSxD6Xy5y3tA+sDqWwAHCA8Lg/rGguPgQh5+MaUPVZIJyVnpAtTuOVYyFxjbskl4vGESpCu+ombzYNlMWm61RQ==)

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://api.washcar.me/v2/oauth2/code/kakao
          naver:
            redirect-uri: https://api.washcar.me/v2/oauth2/code/naver

front-server:
  domain: https://www.washcar.me

cookie:
  domain: washcar.me
