server:
  port: 80

spring:
  jpa:
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  output:
    ansi:
      enabled: always

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            scope:
              - profile_nickname
              - phone_number
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

cookie:
  max-age: 7776000  # 60*60*24*90, 90일

jwt:
  secret: ${JWT_SECRET}

aligo:
  user-id: shim
  sender: ${ALIGO_SENDER}
  api-key: ${ALIGO_API_KEY}
#  test-mode: Y  # 메시지를 전송하지 않고 에러가 나는지만 확인하려면 주석을 해제

#logging:
#  level:
#    root: debug
